export const LOGIN = 'AUTH/LOGIN';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOADING = 'AUTH/LOADING';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const RESET_MESSAGE = 'AUTH/RESET_MESSAGE';
export const UPDATE_PASSWORD = 'AUTH/UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'AUTH/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAIL = 'AUTH/UPDATE_PASSWORD_FAIL';
export const FORGOT_PASSWORD = 'AUTH/FORGOT_PASSWORD';
export const FORGOT_PASSWORD_FAIL = 'AUTH/FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD_SUCCESS = 'AUTH/FORGOT_PASSWORD_SUCCESS';

export const SIGNUP = 'AUTH/SIGNUP';
export const SIGNUP_SUCCESS = 'AUTH/SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'AUTH/SIGNUP_ERROR';

export const GET_USER = 'AUTH/GET_USER';

export const UPDATE_INFO_USER = 'AUTH/UPDATE_USER';
export const UPDATE_INFO_USER_FAIL = 'AUTH/UPDATE_USER_FAIL';
export const UPDATE_INFO_USER_SUCCESS = 'AUTH/UPDATE_USER_SUCCESS';

export const LOGOUT = 'AUTH/LOGOUT';
